version: '3'
services:
  client:
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  landing-page:
    build:
      context: ./landing-page
  books:
    build:
      context: ./books
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '3050:80'
